### PR TITLE
Update ci ready

### PR DESCRIPTION
**Pull request by robyoung**
Update to loosely follow the CI used in the microbit crate.

- Add a CHANGELOG.md and a workflow to verify it is correctly updated.
- Split clippy and rustfmt into separate jobs that only run on stable to avoid the risk of new nightly changes blocking the build.
- Add a minimum supported Rust version (MSRV). Initially using the MSRV from the microbit crate as a starting point.
- Remove the test step as there are no tests
- Add a `bors.toml`. Someone with the power would have to actually add bors.

There are a few changes here. I would be happy to split things out into separate PRs if some are more controversial than others.

### CODE REVIEW

**Review by Yatekii — APPROVED** [review]
Thank you very much :)

bors r+

**Comment by robyoung** [comment]
@Yatekii sorry about that, it should work now.

**Comment by Yatekii** [comment]
bors retry

**Comment by robyoung** [comment]
That looks like a GitHub Actions issue. It looks like it failed to download the `actions/checkout` action! 😕

**Comment by robyoung** [comment]
bors retry

**Comment by Yatekii** [comment]
bors retry

**Comment by Yatekii** [comment]
Sometimes HTTPs is not so reliable ;P

Btw, on topic: I like this very much, thanks for putting in the work! I am kind of not a fan of a MSRV, but it's okay to include it. But I don't like working around keeping an MSRV. I think it's hard enough already to get around nightly with all the cool features it provides =)

**Comment by robyoung** [comment]
Yea, I'm totally with you.  My feeling is that the MSRV is a signal to the user as to what they should expect not a commitment to keep the crate supporting that version. And as a result, there should be no resistance to bumping that MSRV.

**Comment by robyoung** [comment]
Although now that I think about it, I wonder whether it's worth being explicit about that somewhere?

**Comment by Yatekii** [comment]
I am not sure :) Personally I am always on the newest compiler. And if I am not and something fails I am at fault for not using the newest one. I don't know how others handle this :/

**Pull request merged**
